apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: main
  namespace: ledger
  labels:
    app: token
    tier: backend
    component: nodes-main
spec:
  serviceName: main
  replicas: 1
  selector:
    matchLabels:
      component: nodes-main
  template:
    metadata:
      namespace: ledger
      labels:
        app: token
        tier: backend
        component: nodes-main
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        node_pool: pool-default
      containers:
        - name: node
          imagePullPolicy: IfNotPresent
          image: gcr.io/tkn-events/token-ledger:1.8.1
          env:
            - name: TOKEN_CALLBACK_ADDRESS
              value: main.ledger.svc.cluster.local:8081
          ports:
            - name: http
              containerPort: 8080
            - name: rpc
              containerPort: 8081
            - name: health
              containerPort: 8082
          volumeMounts:
            - name: ledger
              mountPath: /usr/share/ledger
          readinessProbe:
            httpGet:
              port: health
              path: /ready
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: health
              path: /live
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: main
        namespace: ledger
        labels:
          app: token
          tier: backend
          component: nodes-main
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi