apiVersion: v1
kind: Service
metadata:
  name: main
  namespace: ledger
  labels:
    app: token
    tier: backend
    component: nodes-main
spec:
  type: NodePort
  selector:
    component: nodes-main
  ports:
    - name: http
      port: 8080
      nodePort: 30100
      protocol: TCP
    - name: rpc
      port: 8081
      nodePort: 30101
      protocol: TCP