apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: peers
  labels:
    app: token
    tier: ledger
    component: peers
    environment: prod
spec:
  serviceName: peers
  replicas: 1
  selector:
    matchLabels:
      tier: ledger
      component: peers
      environment: prod
  template:
    metadata:
      labels:
        app: token
        tier: ledger
        component: peers
        environment: prod
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: peers-node
          imagePullPolicy: IfNotPresent
          image: gcr.io/tkn-events/token-ledger:1.6.1
          env:
            - name: TOKEN_LEDGER
              value: main.ledger-prod:8080
            - name: TOKEN_CALLBACK_ADDRESS
              value: peers.ledger-prod:8080
          ports:
            - name: rpc
              containerPort: 8080
            - name: health
              containerPort: 8081
          volumeMounts:
            - name: ledger
              mountPath: /usr/share/ledger
          readinessProbe:
            httpGet:
              port: 8081
              path: /ready
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 8081
              path: /live
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: ledger
        labels:
          app: token
          tier: ledger
          component: peers
          environment: prod
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi