apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: main
  labels:
    app: token
    system: ledger
    component: main
spec:
  serviceName: main
  replicas: 1
  selector:
    matchLabels:
      system: ledger
      component: main
  template:
    metadata:
      labels:
        app: token
        system: ledger
        component: main
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: main-node
          imagePullPolicy: IfNotPresent
          image: gcr.io/tkn-events/token-ledger:latest
          env:
            - name: TOKEN_CALLBACK_ADDRESS
              #value: token-ledger-master-svc.default.svc.cluster.local
              value: main
          ports:
            - name: rpc
              containerPort: 8080
            - name: health
              containerPort: 8081
          volumeMounts:
            - name: ledger
              mountPath: /usr/share/ledger
          readinessProbe:
            httpGet:
              port: 8081
              path: /ready
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 8081
              path: /live
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: ledger
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi