kind: PersistentVolume
apiVersion: v1
metadata:
  name: token-ledger-pv-001
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"