apiVersion: v1
kind: Service
metadata:
  name: peers
  namespace: ledger-dev
  labels:
    app: token
    tier: ledger
    component: peers
    environment: dev
spec:
  type: ClusterIP
  selector:
    tier: ledger
    component: peers
    environment: dev
  ports:
    - name: rpc
      port: 8081
      targetPort: 8081
      protocol: TCP