FIND_PATH(LIBUV_INCLUDE_DIR NAMES uv.h)
FIND_LIBRARY(LIBUV_LIBRARIES NAMES uv libuv)

if(WIN32)
    list(APPEND LIBUV_LIBRARIES iphlpapi)
    list(APPEND LIBUV_LIBRARIES psapi)
    list(APPEND LIBUV_LIBRARIES userenv)
    list(APPEND LIBUV_LIBRARIES ws2_32)
endif()

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(libuv DEFAULT_MSG LIBUV_LIBRARIES LIBUV_INCLUDE_DIR)